### ISSUE TITLE
Error in signals.py

### ISSUE THREAD

**Issue by vivekkumar15** [shosca/django-sorcery#184]
In the file `signals.py` this line `from blinker._utilities import defaultdict` is failing. Should the `defaultdict` be imported from the `collections` module in python?

**Comment by shosca** [comment]
Yea, it looks like it might not be that straight forward, looks like `blinker==1.6` also has some breaking changes, i'd recommend pinning to `blinker<1.6` for now

**Comment by shosca** [comment]
Fixed in #185
